// Code generated by mockery v2.12.2. DO NOT EDIT.

package mocks

import (
	models "github.com/solutionstack/jobsity-demo/models"
	mock "github.com/stretchr/testify/mock"

	sync "sync"

	testing "testing"
)

// TickBot is an autogenerated mock type for the TickBot type
type TickBot struct {
	mock.Mock
}

// BotMessage provides a mock function with given fields: data
func (_m *TickBot) BotMessage(data models.WsMessage) error {
	ret := _m.Called(data)

	var r0 error
	if rf, ok := ret.Get(0).(func(models.WsMessage) error); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StartWorker provides a mock function with given fields: pm, respChan
func (_m *TickBot) StartWorker(pm *sync.WaitGroup, respChan *chan []byte) {
	_m.Called(pm, respChan)
}

// NewTickBot creates a new instance of TickBot. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewTickBot(t testing.TB) *TickBot {
	mock := &TickBot{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
